apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
spec:
  selector:
    matchLabels:
      app: writer
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: daemon
        image: konica-writer
        imagePullPolicy: Never

