apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: daemon
        image: konica-processor
        imagePullPolicy: Never

