apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader-flask
spec:
  selector:
    matchLabels:
      app: reader-flask
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reader-flask
    spec:
      containers:
      - name: reader
        image: konica-reader
        imagePullPolicy: Never
        ports:
        - containerPort: 2222

---
apiVersion: v1
kind: Service
metadata:
  name: reader-service
  labels:
    app: flask
spec:
  ports:
  - port: 2222
    protocol: TCP
    name: http
  selector:
    app: flask
  type: LoadBalancer
